repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: "book"

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        types:
          - python

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.942'
    hooks:
    - id: mypy
      files: jupyterlab_heavyai/