#!/bin/bash
set -o errexit
set -o xtrace

jlpm install
jlpm run build
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
jupyter labextension install . --no-build
pip install git+https://github.com/Quansight/ibis-vega-transform.git#datetime
pip install -e .
jupyter lab build

