#!/bin/bash
set -o errexit
set -o xtrace

pip install -e . git+https://github.com/saulshanabrook/vega-ibis-transform.git@datetime
jlpm install
jlpm run build
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
jupyter labextension install . --no-build
jupyter lab build

